name: Sample Test Workflow

on:
  push:
    branches: [ "main" ]

env:
  EXCEPTION_LIST: "Rakuten-MTSD-PAIS/rakuten-drive-cloud-transfer Rakuten-MSTD-PAIS/rakuten-drive-billing Rakuten-MSTD-PAIS/rakuten-drive-queue-api Rakuten-MSTD-PAIS/rakuten-drive-email-search Rakuten-MSTD-PAIS/rakuten-drive-microsoft Rakuten-MTSD-PAIS/rakuten-drive-common Rakuten-MTSD-PAIS/rakuten-drive-fe-b2b Rakuten-MTSD-PAIS/rakutenDrive-Devops Rakuten-MTSD-PAIS/forest-transfer Rakuten-MTSD-PAIS/forest-storage Rakuten-MTSD-PAIS/rakuten-drive-api-specs Rakuten-MTSD-PAIS/rakuten-drive-admin Rakuten-MTSD-PAIS/rakutenDrive-GitOps"
  A_LIST: "YEAH"
  
jobs:
    Heyy:
        runs-on: ubuntu-latest
        steps:
            - name: check repo name
              run: |
                echo github.repositoryname : ${{ github.repository }}
            - name: show Exception list
              run: |
                echo "${{env.EXCEPTION_LIST}} ${{env.A_LIST}}"
                echo ${{ contains( "env.EXCEPTION_LIST env.A_LIST", "YEAH" }}
                
            - name: exist?
              if: ${{ !contains( env.EXCEPTION_LIST, github.repository ) }}
              run: |
                echo Ohyeah
            # - name: notexist?
            #   if: contains(${{ env.EXCEPTION_LIST}}, "Rakuten-MTSD-PAIS/rakuten-drive-cloud-transfer")
            #   run: |
            #     echo YES
                
    Composite-Test:
        needs: Heyy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.1.1

            - name: Composite Test
              uses: ./.github/actions/set-common-env/
              with:
                RD_AWS_BOT_ROLE: ${{ secrets.RD_AWS_BOT_ROLE }}

            - name: Node Build
              if: ${{ env.CODE_LANGUAGE == 'nodejs' }}
              uses: ./.github/actions/build-node/

            - name: Go Build
              if: ${{ env.CODE_LANGUAGE == 'golang' }}
              uses: ./.github/actions/build-go/
              
