name: Sample Test Workflow

on:
  push:
    branches: [ "main" ]

jobs:
    Composite-Test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.1.1

            - name: Composite Test
              uses: ./.github/actions/set-common-env-composite/

            - name: see if Composite Test done well
              run: |
                echo "${{ env.CODE_LANGUAGE }}, ${{ env.SERVICE_NAME }}"
                echo "Composite Test done well"