name: Sample Test Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  Hoolah:
    uses: ./.github/workflows/set-common-env.yml
  
  Hello:
    runs-on: ubuntu-latest
    needs: Hoolah
    steps:
        - name: see if Hoolah done well
          run: |
            echo "{{$GITHUB_ENV.CODE_LANGUAGE}}, {{$GITHUB_ENV.SERVICE_NAME}}"
            echo "Hoolah done well"
    # runs-on: ubuntu-latest
    # steps:
    # - name: Checkout Repository
    #   uses: actions/checkout@v4.1.1
    
    # - name: testtest
    # # Check if workflow call runs properly
    #   uses: ./.github/workflows/set-common-env.yml