name: Sample Test Workflow

on:
  push:
    branches: [ "main" ]

jobs:
    Composite-Test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.1.1

            - name: Composite Test
              uses: ./.github/actions/set-common-env/

            - name: can show secrets?
              shell: bash
              run: echo "secrets.RD_AWS_BOT_ROLE=${{ secrets.RD_AWS_BOT_ROLE }}"

            # - name: see if Composite Test done well
            #   run: |
            #     echo "${{ env.CODE_LANGUAGE }}, ${{ env.SERVICE_NAME }}"
            #     echo "Composite Test done well"

            - name: Node Build
              if: ${{ env.CODE_LANGUAGE == 'nodejs' }}
              uses: ./.github/actions/build-node/

            - name: Go Build
              if: ${{ env.CODE_LANGUAGE == 'golang' }}
              uses: ./.github/actions/build-go/
              