name: Sample Test Workflow

on:
  push:
    branches: [ "main" ]

jobs:
    Heyy:
        runs-on: ubuntu-latest
        steps:
            - name: check repo name
              run: |
                echo github.repositoryname : ${{ github.repository }}
                
    Composite-Test:
        needs: Heyy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.1.1

            - name: Composite Test
              uses: ./.github/actions/set-common-env/
              with:
                RD_AWS_BOT_ROLE: ${{ secrets.RD_AWS_BOT_ROLE }}

            - name: Node Build
              if: ${{ env.CODE_LANGUAGE == 'nodejs' }}
              uses: ./.github/actions/build-node/

            - name: Go Build
              if: ${{ env.CODE_LANGUAGE == 'golang' }}
              uses: ./.github/actions/build-go/
              
